services:
    _defaults:
        autowire: true
        autoconfigure: false

    SpiderWeb\Sylius\SendCloudPlugin\Api\SendCloudClient:
        arguments:
            $httpClient: '@http_client'

    SpiderWeb\Sylius\SendCloudPlugin\Calculator\SendCloudShippingCalculator:
        tags:
            - { name: sylius.shipping_calculator, calculator: sendcloud, label: 'spiderweb_sendcloud.ui.calculator_label', form_type: SpiderWeb\Sylius\SendCloudPlugin\Form\Type\SendCloudShippingCalculatorType }

    SpiderWeb\Sylius\SendCloudPlugin\Form\Type\SendCloudShippingCalculatorType:
        tags:
            - { name: form.type }

    SpiderWeb\Sylius\SendCloudPlugin\EventListener\ShipmentShippedListener:
        tags:
            - { name: kernel.event_listener, event: workflow.sylius_shipment.transition.ship, priority: 10 }
